### PR TITLE
Fixed blocking issue after execute the delete operation

### PR DESCRIPTION
**Pull request by zhuxb711**

### CODE REVIEW

**Comment by zhuxb711** [comment]
@Bassman2 Could you please help review this PR?

**Comment by zhuxb711** [comment]
@Bassman2

**Comment by zhuxb711** [comment]
@Bassman2 Would you approve this PR?

**Comment by Bassman2** [comment]
Feature added  with a switch

**Comment by zhuxb711** [comment]
Thanks and looking forward to your new version!

**Pull request closed without merging**
